file_locations:
  metadata_file: data/musicnet_metadata.csv
  midi_gm_mapping_file: data/midi_gm_mapping.csv
  musicnet_data: data/musicnet.npz
  midi_samples: data/midi_samples/
  midi_musicnet: data/midi_musicnet/
  interim_data:
    label_data: data/interim/label_data
    element_data: data/interim/element_data
musicnet:
  sample_rate: 44100
  resolution: 512
